import {
  LayoutDashboard,
  Users,
  FolderKanban,
  HardHat,
  DollarSign,
  Settings,
  Building2,
  User,
  UserCog,
  UserPlus,
  ShoppingBag,
  ListTree,
  Package,
  Wrench,
  FileText,
  Construction,
  Truck,
  Clock,
  CheckCircle2,
  TrendingUp,
  TrendingDown,
  BarChart3,
  Calendar,
  MapPin,
  ShieldX,
  Puzzle,
  Palette,
  Layers,
  Layout,
  BookOpen,
  Search,
  MessageSquare,
  Bell,
  Mail,
  Brain,
  Bot,
  Sparkles,
  History,
  Activity,
  GitBranch,
  Play,
  Webhook,
  Hash,
  CreditCard,
  Globe,
  File,
  Check,
  Send,
  PenTool,
  Image,
  Phone,
  Tag,
  Star,
  PieChart,
  LineChart,
  List,
} from '@/constants/icons';
import type { LucideIcon } from '@/constants/icons';

export interface NavItem {
  href?: string;
  label: string;
  icon: LucideIcon;
  children?: NavItem[];
}

export const companyNavigation: NavItem[] = [
  { href: '/app', label: 'Dashboard', icon: LayoutDashboard },
  {
    label: 'Cadastros',
    icon: Users,
    children: [
      { href: '/app/clientes', label: 'Clientes', icon: Users },
      { href: '/app/fornecedores', label: 'Fornecedores', icon: Truck },
      { href: '/app/equipes', label: 'Equipe', icon: UserCog },
      { href: '/app/parceiros', label: 'Parceiros', icon: UserPlus },
      { href: '/app/produtos', label: 'Produtos', icon: Package },
    ],
  },
  {
    label: 'Catálogo',
    icon: BookOpen,
    children: [
      { href: '/app/catalogo/ambientes', label: 'Ambientes', icon: Layout },
      { href: '/app/catalogo/modulos', label: 'Módulos', icon: Layers },
      { href: '/app/catalogo/materiais', label: 'Materiais', icon: Package },
      { href: '/app/catalogo/acabamentos', label: 'Acabamentos', icon: Palette },
      { href: '/app/catalogo/biblioteca', label: 'Biblioteca', icon: BookOpen },
    ],
  },
  {
    label: 'Comercial',
    icon: DollarSign,
    children: [
      { href: '/app/crm/leads', label: 'Leads', icon: Users },
      { href: '/app/crm', label: 'CRM', icon: MessageSquare },
      { href: '/app/orcamentos', label: 'Orçamentos', icon: FileText },
      { href: '/app/propostas', label: 'Propostas', icon: File },
      { href: '/app/contratos', label: 'Contratos', icon: FileText },
      { href: '/app/vendas', label: 'Vendas', icon: TrendingUp },
    ],
  },
  {
    label: 'Agenda',
    icon: Calendar,
    children: [
      { href: '/app/agenda', label: 'Calendário', icon: Calendar },
      { href: '/app/crm/visitas', label: 'Visitas', icon: MapPin },
      { href: '/app/agenda/reunioes', label: 'Reuniões', icon: Calendar },
      { href: '/app/tarefas', label: 'Tarefas', icon: CheckCircle2 },
    ],
  },
  {
    label: 'Projetos',
    icon: FolderKanban,
    children: [
      { href: '/app/projetos', label: 'Projetos', icon: FolderKanban },
      { href: '/app/projetos/escopos', label: 'Escopos', icon: FileText },
      { href: '/app/projetos/arquivos', label: 'Arquivos', icon: File },
      { href: '/app/projetos/aprovacoes', label: 'Aprovações', icon: Check },
    ],
  },
  {
    label: 'Produção',
    icon: HardHat,
    children: [
      { href: '/app/producao', label: 'Produção', icon: HardHat },
      { href: '/app/os', label: 'Ordens', icon: FileText },
      { href: '/app/producao/fabrica', label: 'Fábrica', icon: Building2 },
      { href: '/app/estoque', label: 'Estoque', icon: Package },
      { href: '/app/compras', label: 'Compras', icon: ShoppingBag },
    ],
  },
  {
    label: 'Instalação',
    icon: Truck,
    children: [
      { href: '/app/instalacoes', label: 'Instalações', icon: Truck },
      { href: '/app/equipes', label: 'Equipes', icon: UserCog },
      { href: '/app/roteiros', label: 'Roteiros', icon: MapPin },
      { href: '/app/pos-venda', label: 'Pós-venda', icon: History },
    ],
  },
  {
    label: 'Financeiro',
    icon: DollarSign,
    children: [
      { href: '/app/financeiro', label: 'Dashboard', icon: LayoutDashboard },
      { href: '/app/financeiro/caixa', label: 'Caixa', icon: DollarSign },
      { href: '/app/financeiro/receber', label: 'Contas a Receber', icon: TrendingUp },
      { href: '/app/financeiro/pagar', label: 'Contas a Pagar', icon: TrendingDown },
      { href: '/app/financeiro/fluxo-caixa', label: 'Fluxo de Caixa', icon: BarChart3 },
      { href: '/app/financeiro/relatorios', label: 'Relatórios', icon: PieChart },
    ],
  },
  {
    label: 'RH',
    icon: Users,
    children: [
      { href: '/app/rh/funcionarios', label: 'Funcionários', icon: Users },
      { href: '/app/rh/cargos', label: 'Cargos', icon: UserCog },
      { href: '/app/admin/permissoes', label: 'Permissões', icon: ShieldX },
      { href: '/app/rh/jornada', label: 'Jornada', icon: Clock },
    ],
  },
  {
    label: 'Empresa',
    icon: Building2,
    children: [
      { href: '/app/empresa', label: 'Dados da Empresa', icon: Building2 },
      { href: '/app/empresa/filiais', label: 'Filiais', icon: Globe },
      { href: '/app/empresa/usuarios', label: 'Usuários', icon: Users },
      { href: '/app/admin/roles', label: 'Papéis', icon: ShieldX },
      { href: '/app/configuracoes', label: 'Configurações', icon: Settings },
    ],
  },
  {
    label: 'Comunicação',
    icon: MessageSquare,
    children: [
      { href: '/app/comunicacao/whatsapp', label: 'WhatsApp', icon: Phone },
      { href: '/app/comunicacao/email', label: 'E-mail', icon: Mail },
      { href: '/app/comunicacao/sms', label: 'SMS', icon: Send },
      { href: '/app/comunicacao/historico', label: 'Histórico', icon: History },
    ],
  },
  {
    label: 'Inteligência Artificial',
    icon: Brain,
    children: [
      { href: '/app/ai', label: 'Assistentes', icon: Bot },
      { href: '/app/ai/prompts', label: 'Prompts', icon: FileText },
      { href: '/app/automacoes-ia', label: 'Automações IA', icon: Sparkles },
      { href: '/app/ai/configuracoes', label: 'Configurações', icon: Settings },
    ],
  },
  {
    label: 'Automações',
    icon: Activity,
    children: [
      { href: '/app/workflows', label: 'Fluxos', icon: GitBranch },
      { href: '/app/workflows/gatilhos', label: 'Gatilhos', icon: Play },
      { href: '/app/workflows/aprovacoes', label: 'Aprovações', icon: Check },
      { href: '/app/integracoes/webhooks', label: 'Webhooks', icon: Webhook },
    ],
  },
  {
    label: 'Relatórios',
    icon: PieChart,
    children: [
      { href: '/app/relatorios/comercial', label: 'Comercial', icon: TrendingUp },
      { href: '/app/relatorios/producao', label: 'Produção', icon: HardHat },
      { href: '/app/relatorios/financeiro', label: 'Financeiro', icon: DollarSign },
      { href: '/app/relatorios/equipe', label: 'Equipe', icon: Users },
      { href: '/app/relatorios/indicadores', label: 'Indicadores', icon: BarChart3 },
    ],
  },
];
