import {
  LayoutDashboard,
  Users,
  FolderKanban,
  HardHat,
  DollarSign,
  Settings,
  ShieldCheck,
  Building2,
  User,
  ShoppingBag,
  ListTree,
  Package,
  UserCog,
  Wrench,
  FileText,
  Construction,
  Truck,
  Clock,
  CheckCircle2,
  TrendingUp,
  TrendingDown,
  BarChart3,
  Calendar,
  MapPin,
  Hash,
  ShieldX,
  AlertCircle,
  UserCheck,
  History,
  Timer,
  Cpu,
  Database,
  Webhook,
  Play,
  GitBranch,
  Activity,
  Bot,
  Brain,
  Sparkles,
  BookOpen,
  Search,
  Puzzle,
  Palette,
  CreditCard,
  Globe,
  MessageSquare,
  Bell,
  Mail,
  Layers,
  Layout,
} from '@/constants/icons';
import type { LucideIcon } from '@/constants/icons';

export interface NavItem {
  href?: string;
  label: string;
  icon: LucideIcon;
  children?: NavItem[];
}

export const mainNavigation: NavItem[] = [
  { href: '/app', label: 'Dashboard', icon: LayoutDashboard },
  {
    label: 'Cadastros',
    icon: Users,
    children: [
      { href: '/app/usuarios', label: 'Usuários', icon: User },
      { href: '/app/clientes', label: 'Clientes', icon: Users },
      { href: '/app/materiais', label: 'Materiais', icon: Package },
      { href: '/app/equipes', label: 'Equipes', icon: UserCog },
      { href: '/app/equipamentos', label: 'Equipamentos', icon: Wrench },
    ],
  },
  {
    label: 'Catálogo',
    icon: ShoppingBag,
    children: [
      { href: '/app/catalogo/categorias', label: 'Categorias', icon: FolderKanban },
      { href: '/app/catalogo/subcategorias', label: 'Subcategorias', icon: ListTree },
      { href: '/app/catalogo/servicos', label: 'Serviços', icon: Package },
    ],
  },
  {
    label: 'Comercial',
    icon: DollarSign,
    children: [
      { href: '/app/crm', label: 'Dashboard', icon: LayoutDashboard },
      { href: '/app/crm/leads', label: 'Leads', icon: Users },
      { href: '/app/crm/agenda', label: 'Agenda Comercial', icon: Calendar },
      { href: '/app/crm/visitas', label: 'Visitas', icon: MapPin },
      { href: '/app/orcamentos', label: 'Orçamentos', icon: FileText },
    ],
  },
  {
    label: 'Agenda',
    icon: Calendar,
    children: [
      { href: '/app/agenda', label: 'Agenda', icon: Calendar },
      { href: '/app/agenda/eventos', label: 'Eventos', icon: FileText },
    ],
  },
  {
    label: 'Produção',
    icon: HardHat,
    children: [
      { href: '/app/producao/painel', label: 'Painel', icon: LayoutDashboard },
      { href: '/app/projetos', label: 'Projetos', icon: FolderKanban },
      { href: '/app/os', label: 'Ordens de Serviço', icon: FileText },
      { href: '/app/producao', label: 'Ordens de Produção', icon: Construction },
      { href: '/app/departamentos', label: 'Departamentos', icon: Building2 },
    ],
  },
  {
    label: 'Instalação',
    icon: Truck,
    children: [
      { href: '/app/instalacoes', label: 'Instalações', icon: Truck },
      { href: '/app/instalacoes/agenda', label: 'Agenda', icon: Clock },
      { href: '/app/instalacoes/entregas', label: 'Entregas', icon: CheckCircle2 },
    ],
  },
  {
    label: 'Financeiro',
    icon: DollarSign,
    children: [
      { href: '/app/financeiro', label: 'Dashboard', icon: LayoutDashboard },
      { href: '/app/financeiro/receber', label: 'Contas a Receber', icon: TrendingUp },
      { href: '/app/financeiro/pagar', label: 'Contas a Pagar', icon: TrendingDown },
      { href: '/app/financeiro/fluxo-caixa', label: 'Fluxo de Caixa', icon: BarChart3 },
      { href: '/app/financeiro/contas', label: 'Contas Bancárias', icon: Building2 },
    ],
  },
  {
    label: 'Administração',
    icon: ShieldX,
    children: [
      { href: '/app/admin', label: 'Dashboard', icon: LayoutDashboard },
      { href: '/app/admin/usuarios', label: 'Usuários', icon: Users },
      { href: '/app/admin/roles', label: 'Papéis', icon: ShieldX },
      { href: '/app/admin/permissoes', label: 'Permissões', icon: FileText },
      { href: '/app/admin/sessoes', label: 'Sessões', icon: UserCheck },
      { href: '/app/admin/auditoria', label: 'Auditoria', icon: History },
      { href: '/app/admin/logs', label: 'Logs', icon: AlertCircle },
    ],
  },
  {
    label: 'Sistema',
    icon: Settings,
    children: [
      { href: '/app/system', label: 'Dashboard', icon: LayoutDashboard },
      { href: '/app/system/monitoring', label: 'Monitoramento', icon: Activity },
      { href: '/app/system/health', label: 'Health Checks', icon: CheckCircle2 },
      { href: '/app/system/logs', label: 'Logs', icon: FileText },
      { href: '/app/system/jobs', label: 'Jobs', icon: Timer },
      { href: '/app/system/scheduler', label: 'Agendamentos', icon: Clock },
      { href: '/app/system/events', label: 'Eventos', icon: Activity },
      { href: '/app/system/workers', label: 'Workers', icon: Cpu },
      { href: '/app/system/deployments', label: 'Deployments', icon: GitBranch },
      { href: '/app/system/backups', label: 'Backups', icon: Database },
    ],
  },
  {
    label: 'Segurança',
    icon: ShieldCheck,
    children: [
      { href: '/app/security/audit', label: 'Auditoria', icon: History },
      { href: '/app/security/logs', label: 'Logs', icon: AlertCircle },
      { href: '/app/security/policies', label: 'Políticas', icon: FileText },
      { href: '/app/security/retention', label: 'Retenção', icon: Database },
      { href: '/app/security/compliance', label: 'Compliance', icon: CheckCircle2 },
    ],
  },
  {
    label: 'Platform',
    icon: ShieldCheck,
    children: [
      { href: '/platform', label: 'Dashboard', icon: LayoutDashboard },
      { href: '/platform/companies', label: 'Empresas', icon: Building2 },
      { href: '/platform/plans', label: 'Planos', icon: FileText },
      { href: '/platform/licenses', label: 'Licenças', icon: CreditCard },
      { href: '/platform/users', label: 'Usuários', icon: Users },
      { href: '/platform/metrics', label: 'Métricas', icon: BarChart3 },
      { href: '/platform/announcements', label: 'Avisos', icon: Bell },
      { href: '/platform/settings', label: 'Configurações', icon: Settings },
    ],
  },
  {
    label: 'Extensões',
    icon: Puzzle,
    children: [
      { href: '/app/plugins/instalados', label: 'Plugins', icon: Puzzle },
      { href: '/app/plugins/marketplace', label: 'Marketplace', icon: ShoppingBag },
      { href: '/app/plugins', label: 'Histórico', icon: History },
    ],
  },
  {
    label: 'Builder',
    icon: Layers,
    children: [
      { href: '/app/builder', label: 'Dashboard', icon: LayoutDashboard },
      { href: '/app/builder/entities', label: 'Entidades', icon: Layers },
      { href: '/app/builder/entities', label: 'Campos', icon: FileText },
      { href: '/app/builder/layouts', label: 'Layouts', icon: Layout },
    ],
  },
  {
    label: 'Empresa',
    icon: Building2,
    children: [
      { href: '/app/empresa', label: 'Dados', icon: Building2 },
      { href: '/app/empresa/plano', label: 'Plano', icon: CreditCard },
      { href: '/app/empresa/personalizacao', label: 'Personalização', icon: Palette },
      { href: '/app/empresa/usuarios', label: 'Usuários', icon: Users },
      { href: '/app/empresa/assinatura', label: 'Assinatura', icon: Globe },
    ],
  },
  {
    label: 'Conhecimento',
    icon: BookOpen,
    children: [
      { href: '/app/knowledge/collections', label: 'Coleções', icon: BookOpen },
      { href: '/app/knowledge/documents', label: 'Documentos', icon: FileText },
      { href: '/app/knowledge/search', label: 'Pesquisas', icon: Search },
      { href: '/app/knowledge/settings', label: 'Configurações', icon: Settings },
    ],
  },
  {
    label: 'Comunicação',
    icon: MessageSquare,
    children: [
      { href: '/app/comunicacao/inbox', label: 'Caixa de Entrada', icon: MessageSquare },
      { href: '/app/comunicacao/conversas', label: 'Conversas', icon: Mail },
      { href: '/app/comunicacao/notificacoes', label: 'Notificações', icon: Bell },
      { href: '/app/comunicacao/templates', label: 'Templates', icon: FileText },
      { href: '/app/comunicacao', label: 'Configurações', icon: Settings },
    ],
  },
  {
    label: 'Inteligência Artificial',
    icon: Brain,
    children: [
      { href: '/app/ai', label: 'Assistente', icon: Bot },
      { href: '/app/ai/chat', label: 'Conversas', icon: Sparkles },
      { href: '/app/ai/prompts', label: 'Prompts', icon: FileText },
      { href: '/app/ai/providers', label: 'Provedores', icon: Settings },
      { href: '/app/ai/history', label: 'Histórico', icon: History },
    ],
  },
  {
    label: 'Automações',
    icon: Activity,
    children: [
      { href: '/app/workflows', label: 'Workflows', icon: GitBranch },
      { href: '/app/workflows/execucoes', label: 'Execuções', icon: Play },
      { href: '/app/workflows/historico', label: 'Histórico', icon: History },
    ],
  },
  {
    label: 'Integrações',
    icon: Webhook,
    children: [
      { href: '/app/integracoes/api', label: 'API Keys', icon: Hash },
      { href: '/app/integracoes/webhooks', label: 'Webhooks', icon: Webhook },
      { href: '/app/integracoes/logs', label: 'Logs', icon: FileText },
      { href: '/app/integracoes/docs', label: 'Documentação', icon: FileText },
    ],
  },
  {
    label: 'Configurações',
    icon: Settings,
    children: [
      { href: '/app/configuracoes/empresa', label: 'Empresa', icon: Building2 },
      { href: '/app/configuracoes/preferencias', label: 'Preferências', icon: Settings },
      { href: '/app/configuracoes/numeracoes', label: 'Numerações', icon: Hash },
      { href: '/app/configuracoes/identidade', label: 'Identidade Visual', icon: FileText },
    ],
  },
];
