export interface RolePermission {
  role: string;
  permissions: string[];
}

export const rolePermissions: RolePermission[] = [
  {
    role: 'SUPER_ADMIN',
    permissions: ['*'],
  },
  {
    role: 'ADMIN',
    permissions: [
      'company.view',
      'company.edit',
      'company.upload_logo',
      'user:*',
      'client:*',
      'project:*',
      'api.view',
      'api.manage',
      'api.keys',
      'api.webhooks',
      'api.logs',
      'workflow.view',
      'workflow.create',
      'workflow.edit',
      'workflow.execute',
      'workflow.logs',
      'ai.view',
      'ai.chat',
      'ai.prompts',
      'ai.providers',
      'ai.history',
      'knowledge.view',
      'knowledge.create',
      'knowledge.upload',
      'knowledge.search',
      'knowledge.manage',
      'plugins.view',
      'plugins.install',
      'plugins.enable',
      'plugins.remove',
      'plugins.marketplace',
      'company.view',
      'company.edit',
      'company.billing',
      'company.settings',
      'company.users',
      'communication.view',
      'communication.send',
      'communication.manage',
      'notifications.manage',
      'templates.manage',
      'builder.view',
      'builder.create',
      'builder.edit',
      'builder.delete',
      'builder.publish',
      'portal.client',
      'portal.employee',
      'mobile.access',
      'mobile.offline',
      'mobile.notifications',
      'jobs.view',
      'jobs.execute',
      'jobs.manage',
      'scheduler.manage',
      'events.view',
      'system.monitoring',
      'system.logs',
      'system.deployments',
      'system.health',
      'system.backups',
      'security.view',
      'security.audit',
      'security.logs',
      'security.policies',
      'security.retention',
      'security.compliance',
      'platform.view',
      'platform.admin',
      'platform.billing',
      'platform.monitoring',
      'platform.licenses',
      'platform.companies',
    ],
  },
  {
    role: 'MANAGER',
    permissions: [
      'company.view',
      'client:view',
      'client:create',
      'client:update',
      'project:*',
    ],
  },
  {
    role: 'TEAM_MEMBER',
    permissions: [
      'company.view',
      'client:view',
      'project:view',
      'project:update',
    ],
  },
  {
    role: 'VIEWER',
    permissions: [
      'company.view',
      'client:view',
      'project:view',
    ],
  },
];
