export const Routes = {
  HOME: '/',
  LOGIN: '/auth/login',
  RECUPERAR_SENHA: '/auth/recuperar-senha',
  CALLBACK: '/auth/callback',

  APP: '/app',
  DASHBOARD: '/app',

  CLIENTES: '/app/clientes',
  CLIENTES_NOVO: '/app/clientes/novo',
  CLIENTES_DETALHE: (id: string) => `/app/clientes/${id}`,
  CLIENTES_EDITAR: (id: string) => `/app/clientes/${id}/editar`,

  PROJETOS: '/app/projetos',
  PROJETOS_NOVO: '/app/projetos/novo',
  PROJETOS_DETALHE: (id: string) => `/app/projetos/${id}`,
  PROJETOS_EDITAR: (id: string) => `/app/projetos/${id}/editar`,

  PRODUCAO: '/app/producao',
  PRODUCAO_NOVO: '/app/producao/novo',
  PRODUCAO_DETALHE: (id: string) => `/app/producao/${id}`,
  PRODUCAO_PAINEL: '/app/producao/painel',

  FINANCEIRO: '/app/financeiro',
  FINANCEIRO_NOVO: '/app/financeiro/novo',
  FINANCEIRO_DETALHE: (id: string) => `/app/financeiro/${id}`,
  FINANCEIRO_RECEBER: '/app/financeiro/receber',
  FINANCEIRO_PAGAR: '/app/financeiro/pagar',
  FINANCEIRO_FLUXO_CAIXA: '/app/financeiro/fluxo-caixa',
  FINANCEIRO_CONTAS: '/app/financeiro/contas',

  USUARIOS: '/app/usuarios',
  USUARIOS_NOVO: '/app/usuarios/novo',
  USUARIOS_DETALHE: (id: string) => `/app/usuarios/${id}`,
  USUARIOS_EDITAR: (id: string) => `/app/usuarios/${id}/editar`,

  MATERIAIS: '/app/materiais',
  EQUIPES: '/app/equipes',
  EQUIPAMENTOS: '/app/equipamentos',
  DEPARTAMENTOS: '/app/departamentos',
  OS: '/app/os',

  CONFIGURACOES: '/app/configuracoes',
  CONFIGURACOES_EMPRESA: '/app/configuracoes/empresa',
  CONFIGURACOES_PREFERENCIAS: '/app/configuracoes/preferencias',
  CONFIGURACOES_NUMERACOES: '/app/configuracoes/numeracoes',
  CONFIGURACOES_IDENTIDADE: '/app/configuracoes/identidade',
  CONFIGURACOES_USUARIOS: '/app/configuracoes/usuarios',
  CONFIGURACOES_USUARIOS_NOVO: '/app/configuracoes/usuarios/novo',
  CONFIGURACOES_USUARIOS_EDITAR: (id: string) => `/app/configuracoes/usuarios/${id}/editar`,
  CONFIGURACOES_PERFIL: '/app/configuracoes/perfil',

  CRM: '/app/crm',
  CRM_NOVO: '/app/crm/novo',
  CRM_DETALHE: (id: string) => `/app/crm/${id}`,
  CRM_LEADS: '/app/crm/leads',
  CRM_LEADS_NOVO: '/app/crm/leads/novo',
  CRM_LEADS_DETALHE: (id: string) => `/app/crm/leads/${id}`,
  CRM_AGENDA: '/app/crm/agenda',
  CRM_VISITAS: '/app/crm/visitas',

  ORCAMENTOS: '/app/orcamentos',
  ORCAMENTOS_NOVO: '/app/orcamentos/novo',
  ORCAMENTOS_DETALHE: (id: string) => `/app/orcamentos/${id}`,

  CATALOGO: '/app/catalogo',
  CATALOGO_CATEGORIAS: '/app/catalogo/categorias',
  CATALOGO_CATEGORIAS_NOVO: '/app/catalogo/categorias/novo',
  CATALOGO_CATEGORIAS_EDITAR: (id: string) => `/app/catalogo/categorias/${id}/editar`,
  CATALOGO_SUBCATEGORIAS: '/app/catalogo/subcategorias',
  CATALOGO_SUBCATEGORIAS_NOVO: '/app/catalogo/subcategorias/novo',
  CATALOGO_SERVICOS: '/app/catalogo/servicos',
  CATALOGO_SERVICOS_NOVO: '/app/catalogo/servicos/novo',

  AGENDA: '/app/agenda',
  AGENDA_EVENTOS: '/app/agenda/eventos',

  INSTALACOES: '/app/instalacoes',
  INSTALACOES_AGENDA: '/app/instalacoes/agenda',
  INSTALACOES_ENTREGAS: '/app/instalacoes/entregas',

  ADMIN: '/app/admin',
  ADMIN_USUARIOS: '/app/admin/usuarios',
  ADMIN_ROLES: '/app/admin/roles',
  ADMIN_PERMISSOES: '/app/admin/permissoes',
  ADMIN_SESSOES: '/app/admin/sessoes',
  ADMIN_AUDITORIA: '/app/admin/auditoria',
  ADMIN_LOGS: '/app/admin/logs',

  TEMPLATES: '/app/templates',
  TEMPLATES_NOVO: '/app/templates/novo',
  TEMPLATES_DETALHE: (id: string) => `/app/templates/${id}`,

  INTEGRACOES: '/app/integracoes',
  INTEGRACOES_API: '/app/integracoes/api',
  INTEGRACOES_WEBHOOKS: '/app/integracoes/webhooks',
  INTEGRACOES_LOGS: '/app/integracoes/logs',
  INTEGRACOES_DOCS: '/app/integracoes/docs',

  WORKFLOWS: '/app/workflows',
  WORKFLOWS_NOVO: '/app/workflows/novo',
  WORKFLOWS_DETALHE: (id: string) => `/app/workflows/${id}`,
  WORKFLOWS_EXECUCOES: '/app/workflows/execucoes',
  WORKFLOWS_HISTORICO: '/app/workflows/historico',

  AI: '/app/ai',
  AI_CHAT: '/app/ai/chat',
  AI_PROMPTS: '/app/ai/prompts',
  AI_PROVIDERS: '/app/ai/providers',
  AI_HISTORY: '/app/ai/history',

  KNOWLEDGE: '/app/knowledge',
  KNOWLEDGE_COLLECTIONS: '/app/knowledge/collections',
  KNOWLEDGE_DOCUMENTS: '/app/knowledge/documents',
  KNOWLEDGE_SEARCH: '/app/knowledge/search',
  KNOWLEDGE_SETTINGS: '/app/knowledge/settings',

  COMUNICACAO: '/app/comunicacao',
  COMUNICACAO_INBOX: '/app/comunicacao/inbox',
  COMUNICACAO_CONVERSAS: '/app/comunicacao/conversas',
  COMUNICACAO_NOTIFICACOES: '/app/comunicacao/notificacoes',
  COMUNICACAO_TEMPLATES: '/app/comunicacao/templates',

  PLUGINS: '/app/plugins',
  PLUGINS_INSTALLED: '/app/plugins/instalados',
  PLUGINS_MARKETPLACE: '/app/plugins/marketplace',
  PLUGINS_DETAIL: '/app/plugins',

  COMPANY: '/app/empresa',
  COMPANY_PLAN: '/app/empresa/plano',
  COMPANY_SETTINGS: '/app/empresa/personalizacao',
  COMPANY_USERS: '/app/empresa/usuarios',
  COMPANY_SUBSCRIPTION: '/app/empresa/assinatura',

  BUILDER: '/app/builder',
  BUILDER_ENTITIES: '/app/builder/entities',
  BUILDER_ENTITIES_NEW: '/app/builder/entities/new',
  BUILDER_ENTITIES_DETAIL: (id: string) => `/app/builder/entities/${id}`,
  BUILDER_LAYOUTS: '/app/builder/layouts',

  SYSTEM_JOBS: '/app/system/jobs',
  SYSTEM_SCHEDULER: '/app/system/scheduler',
  SYSTEM_EVENTS: '/app/system/events',
  SYSTEM_WORKERS: '/app/system/workers',
  SYSTEM_MONITORING: '/app/system/monitoring',
  SYSTEM_LOGS: '/app/system/logs',
  SYSTEM_DEPLOYMENTS: '/app/system/deployments',
  SYSTEM_HEALTH: '/app/system/health',
  SYSTEM_BACKUPS: '/app/system/backups',

  SECURITY: '/app/security',
  SECURITY_AUDIT: '/app/security/audit',
  SECURITY_LOGS: '/app/security/logs',
  SECURITY_POLICIES: '/app/security/policies',
  SECURITY_RETENTION: '/app/security/retention',
  SECURITY_COMPLIANCE: '/app/security/compliance',

  PLATFORM: '/platform',
  PLATFORM_DASHBOARD: '/platform',
  PLATFORM_COMPANIES: '/platform/companies',
  PLATFORM_PLANS: '/platform/plans',
  PLATFORM_LICENSES: '/platform/licenses',
  PLATFORM_USERS: '/platform/users',
  PLATFORM_METRICS: '/platform/metrics',
  PLATFORM_ANNOUNCEMENTS: '/platform/announcements',
  PLATFORM_SETTINGS: '/platform/settings',
} as const;
