export { leadService } from './services/lead-service';
export { activityService } from './services/activity-service';
export { visitService } from './services/visit-service';
export { crmService } from './services/crm-service';
export * from './actions/crm-actions';
export { leadRepository } from './repository/lead-repository';
export { leadActivityRepository } from './repository/lead-activity-repository';
export { visitRepository } from './repository/visit-repository';
export { visitAttachmentRepository } from './repository/visit-attachment-repository';
export { useLeads } from './hooks/use-leads';
export { useLead } from './hooks/use-lead';
export { useLeadActivities } from './hooks/use-lead-activities';
export { useVisits } from './hooks/use-visits';
export { leadSchema, leadStatusSchema, leadTemperatureSchema, activityTypeSchema, visitStatusSchema, measurementSchema, leadFormSchema, leadActivitySchema, leadActivityFormSchema, visitSchema, visitFormSchema, visitAttachmentSchema } from './schemas';
export type { Lead, LeadActivity, Visit, VisitAttachment, Measurement, LeadStatus, LeadTemperature, ActivityType, VisitStatus } from './types';
export { LEAD_STATUS_LABELS, LEAD_STATUS_COLORS, LEAD_TEMPERATURE_LABELS, LEAD_TEMPERATURE_COLORS, ACTIVITY_TYPE_LABELS, ACTIVITY_TYPE_COLORS, VISIT_STATUS_LABELS, VISIT_STATUS_COLORS } from './validators';
export { ActivityTimeline } from './components/ActivityTimeline';
export { LeadStatusBadge, TemperatureBadge } from './components/LeadBadge';
export { LeadDetail } from './components/LeadDetail';
export { LeadTable } from './components/LeadTable';
export { VisitCard } from './components/VisitCard';
